name: proselint

on:
  pull_request:
    branches:
      - main
      
permissions: {}

jobs:
  proselint:
    name: prose
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install proselint
        run: pip install proselint
      - name: Run proselint
        run: proselint *.md
      - run: echo "Passed"